# Generated by Django 5.1.4 on 2024-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='buyer',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
