# Generated by Django 5.1.4 on 2024-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='age',
            field=models.IntegerField(),
        ),
    ]
