# Generated by Django 5.1.4 on 2025-01-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_category_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='content',
            field=models.TextField(default=True),
        ),
    ]
