# Generated by Django 5.1.4 on 2025-01-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_person_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='content',
            field=models.TextField(),
        ),
    ]
